dbname: ram_testing
user: ram
password: fuckingdatabase
host: 192.168.6.157
port: 5440
id_my : 872965519
group_id : -1002259594246
api_token_bot : 7725614078:AAFv71izXkxQ5LKoB28Etrf7rMteYo0dw_I
dataframes : 
  '1': 1.1.1_Бутылки-Прозрачный
  '2': 1.1.2_Бутылка-Светло-Зелёный
  '3': 1.1.3_Бутылка-Голубой
  '4': 1.1.4_Бутылка-Тёмно-Зелёный
  '5': 1.1.5_Бутылка-Коричневый
  '6': 1.1.6_Бутылка-Чёрный
  '7': 1.1.7_Бутылка-Белый
  '8': 1.1.8_Бутылка-От-Масла
  '9': 1.1.9_Бутылка-Нестандарт
  '10': 1.1.10_Бутылка-Этикетка-С-Термоусадкой
  '11': 1.2.1_Крышки-От-Бутылок
  '12': 1.2.2_Флаконы-От-Косметики-И-Химии-Белые
  '13': 1.2.3_Флаконы-От-Косметики-И-Химии-Цветные
  '14': 1.2.4_Канистры-От-Бензина
  '15': 1.2.5_Канистры-От-Масла
  '16': 1.2.6_Товары-Для-Дома-Лейки-Горшки-Контейнеры
  '17': 1.2.7_ПНД-Ведро
  '18': 1.2.8_ПНД-Ящик
  '19': 1.3.1_Прозрачная-Плёнка-И-Пакеты
  '20': 1.3.2_Белые-Пакеты-Для-Продуктов-От-Молока-От-Порошка
  '21': 1.3.3_Цветные-Пакеты
  '22': 1.3.4_Чёрные_Пакеты
  '23': 1.3.5_Шуршащие-Прозрачные-Пакеты
  '24': 1.3.6_Шуршащие-Белые-Пакеты
  '25': 1.3.7_Шуршащие-Цветные-Пакеты
  '26': 1.4.1_Одноразовая-Посуда-Полипропилен
  '27': 1.5.1_Подложки-Под-Продукты-И-Яйца-Полистирол
  '28': 1.6.1_Пластик-Другой
  '29': 1.6.2_Плёнки-Другие
  '30': 2.1.1_Гофрокартон-Упаковочные-Коробки
  '31': 2.1.2_Однослойный-Картон-Втулки-От-ТуалетБумаги-Открытки-Визитки
  '32': 2.2.1_Газетная-Бумага-Газеты-Книги-Тетради
  '33': 2.2.2_Глянцевая-Бумага-Журналы-Буклеты-Календари
  '34': 2.2.3_Офисная-Бумага-Конверты
  '35': 2.3.1_Макулатура-Другая
  '36': 3.1.1_Алюминиевые-Банки
  '37': 3.1.2_Алюминиевые-Балончики
  '38': 3.2.1_Жестяные-Консервные-Банки-Банки-От-Чая
  '39': 3.2.2_Жестяные-Крышки-От-Стеклянных-Банок
  '40': 3.3.1_Металлолом
  '41': 3.4.1_Фольга
  '42': 3.5.1_Металлические-Изделия-Другие
  '43': 4.1.1_Стеклянные-Банки-И-Бутылки-Прозрачные
  '44': 4.1.2_Стеклянные-Бутылки-Зелёные
  '45': 4.1.3_Стеклянные-Бутылки-Коричневые
  '46': 4.1.4_Стеклянные-Изделия-Другие
  '47': 5.1.1_Tetra Pak
  '48': 6.1.1_Текстиль
  '49': 7.1.1_Органические-Отходы
  '50': 8.1.1_Опасные-Отходы
  '51': 9.1.1_Дерево-И-Доски
  '52': 10.1.1_Шины-И-Покрышки
  '53': 11.1.1_Электроприборы
  '54': 12.1.1_Вторсырьё-Другое